import { ItemTag, NestedNamespace } from "../../../../abstractions";
import { namespace as mcNamespace } from "../../namespace";
const namespace = new NestedNamespace("enchantable", mcNamespace);

export const armor = new ItemTag("armor", namespace);
export const bow = new ItemTag("bow", namespace);
export const chestArmor = new ItemTag("chest_armor", namespace);
export const crossbow = new ItemTag("crossbow", namespace);
export const durability = new ItemTag("durability", namespace);
export const equippable = new ItemTag("equippable", namespace);
export const fireAspect = new ItemTag("fire_aspect", namespace);
export const fishing = new ItemTag("fishing", namespace);
export const footArmor = new ItemTag("foot_armor", namespace);
export const headArmor = new ItemTag("head_armor", namespace);
export const legArmor = new ItemTag("leg_armor", namespace);
export const mace = new ItemTag("mace", namespace);
export const mining = new ItemTag("mining", namespace);
export const miningLoot = new ItemTag("mining_loot", namespace);
export const sharpWeapon = new ItemTag("sharp_weapon", namespace);
export const sword = new ItemTag("sword", namespace);
export const trident = new ItemTag("trident", namespace);
export const vanishing = new ItemTag("vanishing", namespace);
export const weapon = new ItemTag("weapon", namespace);
